name: askuenraimobile
description: "UENR Virtual Assistant Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  audioplayers: ^6.5.0
  flutter_tts: ^4.0.2
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
